# TASK #1: Import Libraries and Datasets

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Loading the dataset
banks_df = pd.read_csv('Banks.csv')

# TASK #2: EXPLORE DATASET

In [3]:
# checking the dataset
banks_df

,author,date,location,bank,star,text,like
0,Kyle,31.08.2023,"Magnolia, TX",merrick_bank,5,Very easy to use to view statements and make o...,NaN
1,Julicia,23.08.2023,"Columbus, GA",merrick_bank,5,Merrick Bank has always been good to me for bu...,NaN
2,Karen,2.06.2023,"Marrero, LA",merrick_bank,4,Times are tough for everyone and I have worked...,3.0
3,Brent,29.03.2023,"Moultrie, GA",merrick_bank,5,I can not asked for a better Credit Card Compa...,3.0
4,Sharon,23.11.2022,"Burnham, IL",merrick_bank,5,Updated on 02/10/2023: I was happy to sign for...,3.0
...,...,...,...,...,...,...,...
19266,J.,30.01.2017,"Salem, OR",tcf_bank,1,Paid my 1st payment on time. They sent me a la...,11.0
19267,Destiny,28.01.2017,"Andover, MN",tcf_bank,1,I have banked with TCF for about 4 years now a...,12.0
19268,Sean,25.01.2017,"Bothell, WA",tcf_bank,1,Most inconvenient bank ever. As a business own...,10.0
19269,Edgar,12.01.2017,"Minneapolis, MI",tcf_bank,1,Well I've been with TCF Bank for 3 plus years ...,12.0
19270,edward,2.01.2017,"Suite B, MI",tcf_bank,1,Deposited $800 3 days ago by certified check a...,10.0

In [4]:
banks_df.head()

,author,date,location,bank,star,text,like
0,Kyle,31.08.2023,"Magnolia, TX",merrick_bank,5,Very easy to use to view statements and make o...,NaN
1,Julicia,23.08.2023,"Columbus, GA",merrick_bank,5,Merrick Bank has always been good to me for bu...,NaN
2,Karen,2.06.2023,"Marrero, LA",merrick_bank,4,Times are tough for everyone and I have worked...,3.0
3,Brent,29.03.2023,"Moultrie, GA",merrick_bank,5,I can not asked for a better Credit Card Compa...,3.0
4,Sharon,23.11.2022,"Burnham, IL",merrick_bank,5,Updated on 02/10/2023: I was happy to sign for...,3.0

In [5]:
banks_df.tail()

,author,date,location,bank,star,text,like
19266,J.,30.01.2017,"Salem, OR",tcf_bank,1,Paid my 1st payment on time. They sent me a la...,11.0
19267,Destiny,28.01.2017,"Andover, MN",tcf_bank,1,I have banked with TCF for about 4 years now a...,12.0
19268,Sean,25.01.2017,"Bothell, WA",tcf_bank,1,Most inconvenient bank ever. As a business own...,10.0
19269,Edgar,12.01.2017,"Minneapolis, MI",tcf_bank,1,Well I've been with TCF Bank for 3 plus years ...,12.0
19270,edward,2.01.2017,"Suite B, MI",tcf_bank,1,Deposited $800 3 days ago by certified check a...,10.0

In [6]:
# checking the shape
banks_df.shape

(19271, 7)

In [7]:
banks_df.columns

Index(['author', 'date', 'location', 'bank', 'star', 'text', 'like'], dtype='object')

In [8]:
banks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19271 entries, 0 to 19270
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   author    19269 non-null  object
 1   date      19271 non-null  object
 2   location  19271 non-null  object
 3   bank      19271 non-null  object
 4   star      19271 non-null  int64
 5   text      19181 non-null  object
 6   like      17769 non-null  float64
dtypes: float64(1), int64(1), object(5)
memory usage: 1.0+ MB

In [9]:
banks_df.describe()

               star          like
count  19271.000000  17769.000000
mean       1.432567     11.109291
std        1.151793      8.091683
min        1.000000      2.000000
25%        1.000000      6.000000
50%        1.000000      9.000000
75%        1.000000     14.000000
max        5.000000    248.000000

In [10]:
# checking missing values
banks_df.isnull().sum()

author         2
date           0
location       0
bank           0
star           0
text          90
like        1502
dtype: int64

In [11]:
# checking duplicates row
banks_df.duplicated().sum()

np.int64(0)

In [12]:
# checking unique values
banks_df.nunique()

author       5699
date         2418
location     6286
bank           47
star            5
text        19180
like           79
dtype: int64